version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    ports:
      - 80:80
    container_name: container_web
  app:
    build:
      context: .
      dockerfile: ./docker/local/app/Dockerfile
    ports:
      - 8080:80
    container_name: container_app
    volumes:
       - ./src:/var/www/html
    depends_on:
      - web
      