version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile
    ports:
      - 80:8070
    container_name: container_web
  app:
    build:
      context: .
      dockerfile: ./docker/local/app/Dockerfile
    expose:
      - 8080
    container_name: container_app
    volumes:
       - ./src:/var/www/html
    depends_on:
      - web
      