name: Deploy work flow for Amazon ECS

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECS_WEB_SERVICE: aws-infra-ecs-service2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_NGINX_REPOSITORY: ecs-nginx
  NGINX_TAG: 1.0.3
  ECR_LARAVEL_REPOSITORY: ecs-laravel
  LARAVEL_TAG: 1.0.3

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Dockder Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache docker
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ github.ref }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ github.ref }}-buildx-

    - run: echo ${{ github.ref }}

    - run: echo ${{ github.sha }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_ARN }}'
        
    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ECR_REGISTRY }}

    - name: nginx push to ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_NGINX_REPOSITORY }}:${{ env.NGINX_TAG }}

    - name: laravel push to ECR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_LARAVEL_REPOSITORY }}:${{ env.LARAVEL_TAG }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move cache
      run: |
         rm -rf /tmp/.buildx-cache
         mv /tmp/.buildx-cache-new /tmp/.buildx-cache


