name: cicd work flow for main Amazon ECS

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  ECS_WEB_SERVICE: aws-infra-ecs-service2 
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com
  ECR_WEB_STG_REPOSITORY: stg-web
  ECR_WEB_PRD_REPOSITORY: prd-web
  ECR_APP_STG_REPOSITORY: stg-app
  ECR_APP_PRD_REPOSITORY: prd-app

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.IAM_ROLE_ARN }}'
        
    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v2
      with:
        registry: ${{ env.ECR_REGISTRY }}

    - name: web pull from stg ECR
      run: docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_STG_REPOSITORY }}:stg
    - name: web current datetime tag add image
      run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_STG_REPOSITORY }}:stg ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_PRD_REPOSITORY }}:${{ env.CURRENT_DATETIME }}
    - name: web prd tag add image
      run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_STG_REPOSITORY }}:stg ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_PRD_REPOSITORY }}:prd
    - name: web push to prd ECR
      run: docker push -a ${{ env.ECR_REGISTRY }}/${{ env.ECR_WEB_PRD_REPOSITORY }}

    - name: app pull from stg ECR
      run: docker pull ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_STG_REPOSITORY }}:stg
    - name: app current datetime tag add image
      run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_STG_REPOSITORY }}:stg ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_PRD_REPOSITORY }}:${{ env.CURRENT_DATETIME }}
    - name: app prd tag add image
      run: docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_STG_REPOSITORY }}:stg ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_PRD_REPOSITORY }}:prd
    - name: app push to prd ECR
      run: docker push -a ${{ env.ECR_REGISTRY }}/${{ env.ECR_APP_PRD_REPOSITORY }}
